### ISSUE TITLE
gpuRcuda doesn't compile on Ubuntu 16.04 / R 3.2.3 / CUDA 8

### ISSUE THREAD

**Issue by jberry47** [gpuRcore/gpuRcuda#2]
It's entirely possible that I don't have something set right but I will say that the package 'gpuR' compiled fine and I can use the functions therein. I have two NVIDIA gpus so I thought to get the R package with CUDA in mind but I'm having troubles. Hopefully there is something in the log that will help with debugging. 

> install_github("gpuRcore/gpuRcuda")
> Downloading GitHub repo gpuRcore/gpuRcuda@master
> from URL https://api.github.com/repos/gpuRcore/gpuRcuda/zipball/master
> Installing gpuRcuda
> '/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>   '/tmp/RtmpXlmiSi/devtools3a831af202e4/gpuRcore-gpuRcuda-1efc193'  \
>   --library='/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 
- installing _source_ package ‘gpuRcuda’ ...
  checking for g++... g++
  checking whether the C++ compiler works... yes
  checking for C++ compiler default output file name... a.out
  checking for suffix of executables... 
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C++ compiler... yes
  checking whether g++ accepts -g... yes
  checking how to run the C++ preprocessor... g++ -E
  Checking for C++ Compiler
  checking whether we are using the GNU C++ compiler... (cached) yes
  checking whether g++ accepts -g... (cached) yes
  checking "Checking environment variable CUDA_HOME"... "CUDA_HOME not set; using highest version found /usr/local/cuda-8.0"
  checking for /usr/local/cuda-8.0/bin/nvcc... yes
  "NVCC found"
  checking "whether this is the 64 bit linux version of CUDA"... checking for /usr/local/cuda-8.0/lib64/libcudart.so... yes
  "yes -- using /usr/local/cuda-8.0/lib64 for CUDA libs"
  checking for Rscript... yes
  checking "building the nvcc command line"... configure: Building Makevars
  configure: creating ./config.status
  config.status: creating src/Makevars
  *\* libs
  /usr/local/cuda-8.0/bin/nvcc -arch=sm_30 -Xcompiler -fPIC -Xcudafe --diag_suppress=boolean_controlling_expr_is_constant -I/usr/share/R/include -I/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include -I"/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/RcppEigen/include" -I/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/RViennaCL/include vcl_drowSums.cu -c
  /home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/r_cast.h(108): warning: statement is unreachable

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/algorithm.h(153): warning: type qualifier on return type is meaningless

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/algorithm.h(154): warning: type qualifier on return type is meaningless

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/algorithm.h(162): warning: type qualifier on return type is meaningless

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/algorithm.h(163): warning: type qualifier on return type is meaningless

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/r_cast.h(62): warning: statement is unreachable

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/vector/vector_from_string.h(42): warning: statement is unreachable

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/r_cast.h(46): warning: statement is unreachable

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/r_cast.h(62): warning: statement is unreachable

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/r_cast.h(108): warning: statement is unreachable

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/internal/wrap.h(528): warning: statement is unreachable

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/Environment.h(95): warning: statement is unreachable

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/vector/vector_from_string.h(42): warning: statement is unreachable

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/vector/Vector.h(311): warning: statement is unreachable

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/vector/proxy.h(99): error: the object has type qualifiers that are not compatible with the member function "Rcpp::internal::string_name_proxy<RTYPE>::get"
            object type is: const Rcpp::internal::string_name_proxy<RTYPE>

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/algorithm.h(153): warning: type qualifier on return type is meaningless

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/algorithm.h(154): warning: type qualifier on return type is meaningless

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/algorithm.h(162): warning: type qualifier on return type is meaningless

/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/algorithm.h(163): warning: type qualifier on return type is meaningless

1 error detected in the compilation of "/tmp/tmpxft_0000335b_00000000-5_vcl_drowSums.cpp4.ii".
Makevars:30: recipe for target 'vcl_drowSums.o' failed
make: **\* [vcl_drowSums.o] Error 2
ERROR: compilation failed for package ‘gpuRcuda’
- removing ‘/home/jeffrey/R/x86_64-pc-linux-gnu-library/3.2/gpuRcuda’
  Error: Command failed (1)

**Comment by cdeterman** [comment]
Ah crap, I just looked at this locally on my machine now.  It appears NVIDIA's 'special' compiler 'nvcc' is causing more problems.  I had previously updated `RViennaCL` to use `Rcpp` to handle all the standard output messages as is standard practice in R and completely fine by C++ standards.  However it appears the `nvcc` compiler is upset with `Rcpp` is included in a `.cu` file. 

At the moment I am not sure how to fix this.  I need to keep `Rcpp` in `RViennaCL` so that is a non-starter.  Perhaps there is a way to make `nvcc` be okay with the `Rcpp` files.  I will need to experiment.  This package has been quite neglected as any precious spare time I get has been devoted to getting `gpuR` updated.

**Comment by cdeterman** [comment]
To keep things updated, I have filed a bug report with NVIDIA.  Hopefully it can be resolved.  I have another 'nuclear' option which I think would get it to work by essentially removing all the possible error messages from the ViennaCL backend.  I could possibly do this be have some `#ifdefined` statements for the compiler around the `Rcpp` elements.   But I clearly don't want to do that unless it is absolutely necessary as it eliminates a very important part of this code.

**Comment by t-pollington** [comment]
Dear @cdeterman, have you got any quick workarounds for this bug? Would love to use gpuRcuda() on my NVIDIA card but at the mo am going to try using gpuR() with openCL instead.

**Comment by cdeterman** [comment]
Hi @t-pollington, I have an idea for a workaround but it is not a 'quick' fix either.  I need to update the header files in `gpuR` that will be linked to in this package to handle the `Rcpp` elements.  I have been dragging my feet at the moment.  NVIDIA just notified me that a bug fix for this has been tested for the newest CUDA toolkit that will be released.  I will still likely implement the workaround for older cards that aren't able to use the newest toolkit.  I have just been too busy with work and addressing `gpuR` to give `gpuRcuda` the attention it needs.  I am hoping to in the coming weeks.  

That said, the OpenCL in `gpuR` is quite optimized and previous benchmarks with the raw `viennacl` code show the performances are similar.  There are situations where the `CUDA` backend will be faster and I intend to make that possible.  Apologies for the delay on this package.

**Comment by mjmg** [comment]
@t-pollington maybe you can try the gmatrix package for the meantime while gpuRcuda is still in limbo; with the limitation that it is Linux only and you need NVIDIA compute 2.0 at minimum and CUDA 7.0 or later for the solvers.
