### ISSUE TITLE
build error thrust missing

### ISSUE THREAD

**Issue by gaodianzhuo** [gpuRcore/gpuRcuda#4]
win10
R version 3.4.2 (2017-09-28) -- "Short Summer"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

ERROR: dependency 'thrust' is not available for package 'gpuRcuda'

**Comment by cdeterman** [comment]
The new implementation requires the `thrust` package which is not yet released to CRAN (it should sometime this month).  In the mean time you can install it from github with:

```r
devtools::install_github('wrathematics/thrust')
```
